### ISSUE TITLE
What does this Connect and Print do?

### ISSUE THREAD

**Issue by leoheck** [Maxinger15/connectandprint#1]
Hi, I saw this new plugin and I am wondering what it does exactly that we don't have yet. Or maybe this is just to have an alternative option to the existing things. 

For instance. I slice my parts on Cura, and after, it offers me to `Print with Octoprint` button.
Then, after clicking this button, it uploads the sliced object (GCode) to the printer.
It turns the PSU of the printer on, but the serial is already connected since it is connected through the Raspberry Pi.
Then, after it starts to print. 
After the print ends, it waits a bit and then turns the PSU off.

**Comment by Eenie75** [comment]
Hi there!

Not the author, but I just happened to download the plug-in today to solve an issue I've had with OctoPrint in a while with my PrusaMini.

When OctoPrint connects to my PrusaMini, the GUI on the Mini basically locks down and I can't control any of the manual functions easily.  So I have to disconnect from OctoPrint, to be able to use the GUI easily.  Usually I forget about that, and when I go to print, the printer is not connected, so I have to fire up my browser and go into OctoPrint and click connect.  Then retry the print job from PrusaSlicer, or use the gui to resubmit.

After installing this plug-in, I intentionally left my printer disconnected after I changed the filament in it.  When I clicked the send to printer in PrusaSlicer, I watched the screen in OctoPrint, as it lit up after getting the job and connected to my printer itself.

That was what I was looking for to happen, if there was already a setting in OctoPrint that provides that functionality please let me know as I was not aware of that feature.

P.S. I don't have mine set up with PSU switching or anything, I like the idea though, I'll have to do some research on it.

**Comment by Maxinger15** [comment]
What @Eenie75 mentioned was ma struggle to. I turn of the power of my 3D Printers but not from my Raspis which run Octoprint.
Everytime I wanted to print something I had to open the webinterface of octoprint just to press the connect button.
This plugin resolves that step because it connects automaticly to the printer if you send a gcode file via the rest api (what cura/prusa slicer does).

I haven´t found setting in octoprint that does that so I have written that plugin.

**Comment by leoheck** [comment]
Ah, ok, so it is an alternative to something I already use. Thanks, guys

This is the way I am setting up my stuff. It is been like this for a couple of years now.

I have a Raspberry Pi connected to a relay, that I managed to connect in between the PSU Power cable.
So, I can turn the PSU on/off with the Raspberry Pi.

The Raspberry Pi is always on, and my Ender 3, is connected to it through a USB Cable. 
This keeps the display of the Ender 3 always on if you don't remove the power pin of the USB Cable.
But it is also good since the Serial Device is always "connected" and then the octoprint does not have to look for it or connect it every time.

Then I have:
- Cura with `Octoprint Connection` plugin
- Octoprint with `PSU Control` plugin

The `Octoprint Connection` has these settings (they are greyed out now, but it is readable)
![image](https://user-images.githubusercontent.com/1277920/235318326-cf06c857-55e5-4700-91c8-7bc7abb4c775.png)

And the `PSU Control` these:
![image](https://user-images.githubusercontent.com/1277920/235318354-a342531d-5631-461f-ab39-f626caec6a25.png)

But if you use a different slicer, then it might be the case that thins have to be different as you were describing.
