### ISSUE TITLE
Automatic update failed

### ISSUE THREAD

**Issue by chemixt** [Maxinger15/connectandprint#11]
While updated most recent version update failed. 
Updating, please wait.

+++++++++++++++++++++++++++++++++++++++
Now updating Connect And Print to 1.2.0
+++++++++++++++++++++++++++++++++++++++
/home/pi/oprint/bin/python -m pip --disable-pip-version-check install https://raw.githubusercontent.com/Maxinger15/connectandprint/1.2.0/connectandprint.py --no-cache-dir
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting https://raw.githubusercontent.com/Maxinger15/connectandprint/1.2.0/connectandprint.py
Downloading https://raw.githubusercontent.com/Maxinger15/connectandprint/1.2.0/connectandprint.py (3.2 kB)
ERROR: Cannot unpack file /tmp/pip-unpack-z3aaqym6/connectandprint.py (downloaded from /tmp/pip-req-build-66f5qa6v, content-type: text/plain; charset=utf-8); cannot detect archive format
ERROR: Cannot determine archive format of /tmp/pip-req-build-66f5qa6v

The update did not finish successfully. Please consult <code>octoprint.log</code> and <code>plugin_softwareupdate_console.log</code> for details.
[octoprint-logs.zip](https://github.com/Maxinger15/connectandprint/files/11962793/octoprint-logs.zip)
[octoprint-logs.zip](https://github.com/Maxinger15/connectandprint/files/11962794/octoprint-logs.zip)

**Comment by Maxinger15** [comment]
Hi, please uninstall the plugin and install it again. The old automatic update method was wrong.
More info: #6
