### ISSUE TITLE
Ensure compatibility with PSU Control

### ISSUE THREAD

**Issue by jeloneal** [Maxinger15/connectandprint#12]
Judging from the readme, your plugin is supposed to work with PSU Control, powering on the printer via that plugin. PSU Control itself already supports a mechanism to connect to the printer after powering it on and also start the print job afterwards. Although it seems to have some problems form time to time starting the job.

I hope your plugin can solve these problems. In order to have it working correctly with PSU Control, what settings do I need to take in PSU Control to make sure both plugins don't interfere with each other?

These are my current settings that work when using just PSU Control.

![image](https://github.com/Maxinger15/connectandprint/assets/48490942/93150541-bf41-4696-a95c-0f085b00ba01)

**Comment by Maxinger15** [comment]
Hi,
with your psu control config it should work right away. Just install my plugin and you are done.
If you encounter problems just let me know.

**Comment by jeloneal** [comment]
Thanks for clarification. Will report back if there are any issues encountered.
