### ISSUE TITLE
Can we distinguish between "Upload" and "Upload and Print" when using PrusaSlicer?

### ISSUE THREAD

**Issue by Defozo** [Maxinger15/connectandprint#3]
I noticed that the plugin starts the print when I click on "Upload" in PrusaSlicer.
Can we instead make it so it connects to the printer and starts the print only when I click "Upload and Print"?

**Comment by Maxinger15** [comment]
Hi,
sure, as far as I can see this can be implemented using the print property of the payload from the [upload event](https://docs.octoprint.org/en/master/events/index.html#file-handling). 
I will verify and implement that in the afternoon.
