### ISSUE TITLE
Plugin Update Broken

### ISSUE THREAD

**Issue by ajfili** [Maxinger15/connectandprint#9]
I had issues updating previously, saw the closed issues about blowing out the old install and reinstalling from scratch. Did that and now this is what I see in OctoPrint Software Update: 
![connect and print screenshot](https://github.com/Maxinger15/connectandprint/assets/75687854/e4034336-98f6-44fd-870f-7eb5fed26639)

**Comment by Maxinger15** [comment]
yeah, I am aware of that. I already opend a issue at the [octoprint repo ](https://github.com/OctoPrint/OctoPrint/issues/4806).
I implemented the update feature according to the docs so I have no clue what causes that.

**Comment by ajfili** [comment]
Ok thanks! Didn't see this specific issue called out after your last update, wanted to make you aware just in case.
